### ISSUE TITLE
getSchema crashes on loading

### ISSUE THREAD

**Issue by dfioravanti** [SoftwareBrothers/adminjs-sql#7]
Hey first at all, thanks for this great library. I am playing around with the SQL connector and for me is crashing on 

```
file:///<PATH>/node_modules/@adminjs/sql/lib/dialects/postgres.parser.js:80
         return result.rows?.schema_name.toString();
```

from debugging it it look like it is because `rows` it is a list and you need to do something like

```ts
return result.rows[0]?.schema_name.toString();
```

but I am not 100% sure it is correct as I do not know exactly how `?` works. In kotlin it would be `rows?[0]` but if I do that the compiler is not happy.

**Comment by dziraf** [comment]
@dfioravanti  Hi, my bad, I merged "custom schema name" PR a few days ago believing everything was alright with it but it seems I'll have to run every code manually now... I've just released a hotfix which worked for me locally, please take a look.

**Comment by dfioravanti** [comment]
Hey @dziraf thanks a lot for the super quick reply. So it seams to work now but it still hangs like I wrote in the other bug but I think that has something to do with my set up. If I figure out it is a but I will let you know. Thanks again
